import { Category } from './category';
import { Tag } from './tag';
import { Media } from './media';

export interface Article {
  id: number;
  uuid: string;
  title: string;
  slug: string;
  body: string;
  original_url: string | null;
  hero_image_url?: string | null; // Dynamically generated by HasMedia trait for the 'hero' collection
  is_pinned: boolean;
  is_featured: boolean;
  view_count: number;
  reading_time?: number;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  category?: Category[];
  tags?: Tag[];
  media?: Media[];
} 